esphome:
  name: stiebel-eltron
  friendly_name: Stiebel Eltron

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

logger:
  logs:
    wifi: WARN
    esp32.preferences: WARN
    WiFiGeneric.cpp: WARN
    light: INFO
    status_led: INFO

api:
  encryption:
    key: !secret api_key

ota:
  - platform: esphome
    password: !secret ota_key

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "Stiebel-Eltron Fallback Hotspot"
    password: !secret fallback_wifi_password

captive_portal:

web_server:
  port: 80

external_components:
  - source:
      type: local
      path: components
    components:
      - stiebel_eltron_can

light:
  - platform: status_led
    id: status_led_light
    pin:
      number: GPIO08
      inverted: true
    internal: true

canbus:
  - platform: esp32_can
    id: can_bus
    rx_pin: GPIO00
    tx_pin: GPIO01
    can_id: 0x680
    bit_rate: 50kbps
    rx_queue_len: 16
    tx_queue_len: 16

stiebel_eltron_can:
  id: stiebel_eltron_component
  canbus_id: can_bus
  status_led: status_led_light

packages:
  - !include ./se-wpe-i-12-h-230-premium.yaml